### ISSUE TITLE
请问用什么工具保持在后台运行比较好

### ISSUE THREAD

**Issue by mxm145** [ihexxa/quickshare#1]
以前用python的时候用suprevisor来监控，没用过go，不知道有什么好用的

**Comment by ihexxa** [comment]
感觉这类工具并不限制于语言, 比如upstart或者systemmd, 是个进程就能管起来.
go这方面的工具见是见到过有人做, 倒是没怎么听到在生产环境用..可能我比较out.
既然不是issue我就先关了. :)
