### ISSUE TITLE
请问有没有可以查看日志的地方

### ISSUE THREAD

**Issue by mxm145** [ihexxa/quickshare#12]
请问有没有可以查看日志的地方，最近老是提示：fail to upload,retrying...

**Comment by mxm145** [comment]
发现文件大小超过10M，无法上传，找了配置文件也没有限制文件大小的地方

**Comment by ihexxa** [comment]
@mxm145 目前后台就是直接打印日志, 需要把它重定向出来, 前台的错误日志目前没有发到后台去, 只能通过从console去查看.
对文件大小是没有限制的(只要你上传机器的文件系统没有文件大小的限制), 可以把后台的打印日志和浏览器console日志贴出来看看.

**Comment by mxm145** [comment]
应该是我本地的上行速度问题导致的，console目前启动的时候会提示这些
`
[root@VM_0_3_centos quickshare]# ./quickshare
config.HostName is empty(""), choose one IP for listening automatically.
2018/07/15 19:45:09 quickshare starts @ 172.16.0.3:8888
2018/07/15 19:45:09 exec: "xdg-open": executable file not found in $PATH
`

**Comment by mxm145** [comment]
还有一个希望能支持多用户

**Comment by mxm145** [comment]
@ihexxa 之前没有重定向日志，等下次遇到了再找一下看看，期待新版

**Comment by brownchow** [comment]
后台的日志可以使用一些日志组件，将日志写入文件中

**Comment by ihexxa** [comment]
已支持日志文件 (#42), 重写了上传逻辑, 虽然没法merge也感谢brownchow的pr.
