### ISSUE TITLE
how to disable predefined users

### ISSUE THREAD

**Issue by WLun001** [ihexxa/quickshare#122]
https://github.com/ihexxa/quickshare/blob/65da92aece7ac78a493b19d07d8a02c7ccbdb54d/configs/docker.yml#L32

**Comment by WLun001** [comment]
or how to edit default docker.yml config

**Comment by WLun001** [comment]
found out able to achieve it with volume mount, but need to provide full config
```
-v ./my-config.yml:/quickshare/docker.yml
```

**Comment by ihexxa** [comment]
Let me check the config merging part.
The configuration part is not so friendly currently, I'll improve it at some time.
