### ISSUE TITLE
captchaEnabled config partially working

### ISSUE THREAD

**Issue by WLun001** [ihexxa/quickshare#123]
`captchaEnabled` should be inside `users` level
https://github.com/ihexxa/quickshare/blob/65da92aece7ac78a493b19d07d8a02c7ccbdb54d/src/server/config.go#L27

but the config is provided at `server` level
https://github.com/ihexxa/quickshare/blob/65da92aece7ac78a493b19d07d8a02c7ccbdb54d/configs/docker.yml#L17

even if set to `captchaEnabled: false` at user level, at login UI still can see it
but able to click `Login` without providing captcha

![image](https://user-images.githubusercontent.com/23547929/150914883-e712c55b-653b-4753-b706-210beb6342ae.png)

**Comment by ihexxa** [comment]
I'll submit a fix for this, thanks for the feedback!
