### ISSUE TITLE
请问可以增加自动重命名的功能吗？

### ISSUE THREAD

**Issue by mxm145** [ihexxa/quickshare#13]
目前上传文件时如果名称与以前的相同会不能上传，能否按照时间或者其他条件自动进行重命名？

**Comment by ihexxa** [comment]
3年零2天, 迟到总比没有好 😆 

如果重名文件已存在，`path/dup_file`  会被命名为 `path/dup_file_1`, `path/dup_file_2`...`path/dup_file_1024`

**Comment by ihexxa** [comment]
There is an issue in css loader.

**Comment by ihexxa** [comment]
Fixed in 0.3.9
