### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by mxm145** [ihexxa/quickshare#45]
经过测试，下载mp3文件会直接成file文件，后缀名没有了，文件名也没了。word，excel直接下载成一个文件夹了

**Comment by ihexxa** [comment]
第一个问题是已知的-_-，第二个是未知的，感谢告知。
估计是跟golang的DetectContentType相关，把excel判断成了zip。
周末修一下。

**Comment by ihexxa** [comment]
New version is [released here](https://github.com/ihexxa/quickshare/releases/tag/0.3.7).
