### ISSUE TITLE
feature request: 能不能在reset或者regenrate按钮后面加一个copy的按钮

### ISSUE THREAD

**Issue by mxm145** [ihexxa/quickshare#8]
几天用下来非常好用，只是要复制链接的时候不是很方便，能不能在reset或者regenrate按钮后面加一个copy的按钮，可以直接复制地址

**Comment by ihexxa** [comment]
@mxm145 之前因为撸的比较匆忙, 这块代码不完善注掉了. 加上确实会方便不少. 争取下个版本加进去.

**Comment by ihexxa** [comment]
Fixed in PR #10
